#!/usr/bin/env node
const { writeFileSync, chmodSync, existsSync, mkdirSync } = require('fs');
const { join } = require('path');

const repoRoot = process.cwd();
const hooksDir = join(repoRoot, '.git', 'hooks');
if (!existsSync(hooksDir)) {
  mkdirSync(hooksDir, { recursive: true });
}

const preCommitPath = join(hooksDir, 'pre-commit');
const script = `#!/bin/sh
# Auto-generated by scripts/install-hooks.js

npm run type-check >/dev/null 2>&1
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo "Pre-commit hook: type-check failed"
  exit $RESULT
fi

npm run build:dev >/dev/null 2>&1
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo "Pre-commit hook: build failed"
  exit $RESULT
fi

exit 0
`;

writeFileSync(preCommitPath, script, { mode: 0o755 });
chmodSync(preCommitPath, 0o755);
console.log('Git hooks installed.');
